<option value="Shonen">Shonen</option>
<option value="Shojo">Shojo</option>
<option value="Seinen">Seinen</option>
<option value="Josei">Josei</option>
<option value="Kodomomuke">Kodomomuke</option>
<option value="Isekai">Isekai</option>
<option value="Mecha">Mecha</option>
<option value="Fantasía">Fantasía</option>
<option value="Ciencia ficción">Ciencia ficción</option>
<option value="Romance">Romance</option>
<option value="Slice of life">Slice of life</option>
<option value="Comedia">Comedia</option>
<option value="Drama">Drama</option>
<option value="Aventuras">Aventuras</option>
<option value="Horror">Horror</option>
<option value="Supernatural">Supernatural</option>
<option value="Misterio">Misterio</option>
<option value="Psicológico">Psicológico</option>
<option value="Historical">Historical</option>
<option value="Musical">Musical</option>
<option value="Yaoi">Yaoi</option>
<option value="Yuri">Yuri</option>
<option value="Deportivo">Deportivo</option>
<option value="Ninjas">Ninjas</option>
<option value="Pelea">Pelea</option>
