<option value="Histórico">Histórico</option>
<option value="Biográfico">Biográfico</option>
<option value="Científico">Científico</option>
<option value="Ambiental">Ambiental</option>
<option value="Social">Social</option>
<option value="Político">Político</option>
<option value="Viajes">Viajes</option>
<option value="Arte">Arte</option>
<option value="Tecnología">Tecnología</option>
<option value="Deportes">Deportes</option>
<option value="Salud">Salud</option>
<option value="Crimen">Crimen</option>
<option value="Ciencia Ficción">Ciencia Ficción</option>
<option value="Música">Música</option>
<option value="Comida">Comida</option>
<option value="Educativo">Educativo</option>
<option value="Deportes Extremos">Deportes Extremos</option>
<option value="Guerra">Guerra</option>
<option value="Investigación">Investigación</option>
<option value="Filosofía">Filosofía</option>
