<option value="Comedia">Comedia</option>
<option value="Drama">Drama</option>
<option value="Suspense">Suspense</option>
<option value="Acción">Acción</option>
<option value="Aventuras">Aventuras</option>
<option value="Ciencia ficción">Ciencia ficción</option>
<option value="No ficción">No ficción</option>
<option value="Fantasía">Fantasía</option>
<option value="Novela">Novela</option>
<option value="Terror">Terror</option>
<option value="Prosa">Prosa</option>
<option value="Poesía">Poesía</option>
<option value="Animación">Animación</option>
<option value="Religiosa">Religiosa</option>
<option value="Futurista">Futurista</option>
<option value="Policíaca">Policíaca</option>
<option value="Crimen">Crimen</option>
<option value="Bélica">Bélica</option>
<option value="Histórica">Histórica</option>
<option value="Deportiva">Deportiva</option>
<option value="Western">Western</option>
<option value="Poema">Poema</option>
