<option value="Pop">Pop</option>
<option value="Rock">Rock</option>
<option value="Jazz">Jazz</option>
<option value="Blues">Blues</option>
<option value="R&B">R&B (Rhythm and Blues)</option>
<option value="Hip Hop">Hip Hop</option>
<option value="Rap">Rap</option>
<option value="Country">Country</option>
<option value="Folk">Folk</option>
<option value="Clasica">Clásica</option>
<option value="Electronica">Electrónica</option>
<option value="Dance">Dance</option>
<option value="Reggae">Reggae</option>
<option value="Soul">Soul</option>
<option value="Funk">Funk</option>
<option value="Metal">Metal</option>
<option value="Punk">Punk</option>
<option value="Indie">Indie</option>
<option value="Gospel">Gospel</option>
<option value="JPop">J-Pop (Pop japonés)</option>
<option value="KPop">K-Pop (Pop coreano)</option>
<option value="WorldMusic">World Music</option>
<option value="Latina">Latina</option>
<option value="Experimental">Experimental</option>
<option value="Alternativa">Alternativa</option>
<option value="Ambiental">Ambiental</option>
<option value="Instrumental">Instrumental</option>
<option value="BluesRock">Blues Rock</option>
<option value="CountryRock">Country Rock</option>
<option value="HardRock">Hard Rock</option>
<option value="HeavyMetal">Heavy Metal</option>
<option value="RapRock">Rap Rock</option>
<option value="RapMetal">Rap Metal</option>
<option value="PopRock">Pop-Rock</option>
<option value="IndieRock">Indie Rock</option>
<option value="FolkRock">Folk Rock</option>
<option value="EDM">Electronic Dance Music (EDM)</option>
<option value="House">House</option>
<option value="Techno">Techno</option>
<option value="Trance">Trance</option>
