<option value="Comedia"></option>
<option value="Drama"></option>
<option value="Suspense"></option>
<option value="Acción"></option>
<option value="Aventuras"></option>
<option value="Ciencia ficción"></option>
<option value="No ficción"></option>
<option value="Fantasía"></option>
<option value="Musical"></option>
<option value="Terror"></option>
<option value="Cine mudo"></option>
<option value="Película 3D"></option>
<option value="Animación"></option>
<option value="Religiosa"></option>
<option value="Futurista"></option>
<option value="Policíaca"></option>
<option value="Crimen"></option>
<option value="Bélica"></option>
<option value="Histórica"></option>
<option value="Deportiva"></option>
<option value="Western"></option>
